apiVersion: v1
kind: Pod
metadata:
  annotations:
    updateNSG: "true"
  name: app
spec:
  containers:
  - image: nginx
    name: app
    resources:
      limits:
        cpu: "250m"
        memory: "100Mi"
    ports:
      - containerPort: 80
  hostNetwork: true
