apiVersion: v1
kind: Pod
metadata:
  labels:
    updateNSG: "true"
  name: app
spec:
  containers:
  - image: node:alpine
    name: app
    command: ['npx', '-y', 'serve', '-p', '8080']
    resources:
      limits:
        cpu: "250m"
        memory: "100Mi"
    ports:
      - containerPort: 8080
  hostNetwork: true
